name = "MeanFieldToolkit"
uuid = "b00fcea2-f4b1-4480-b444-a0ed31c44801"
authors = ["Anjishnu Bose", "Samuel Vadnais"]
version = "1.1.2"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FixedPointToolkit = "081f7a28-ac82-48c1-a10e-fa8b3349a52a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TightBindingToolkit = "2233325a-6eb3-486f-aff0-670e0939fa7e"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
Distributions = "^0.25"
Statistics = "1.0 - 2.0"
Tullio = "^0.3"
Logging = "^1.6.7"
Plots = "^1.38"
FixedPointToolkit = "^1"
TightBindingToolkit = "^2.3.4"
julia = "^1.7, ^1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
